// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-indent-string/9d6fef8eeccf2b9d9690b29b9730635ccef1b43c/index.d.ts
declare module 'indent-string' {
function indentString (string: string, indent: string, count?: number): string;

export = indentString;
}
